# orbit custom configuration
file-tree-initial-width = 0.2
initial-view = "split"
incremental-fold-lines = 20

[keybindings.file-tree]
quit = "q"
tree-shrink = "["
tree-grow = "]"
comment-list = "c"
prompt-preview = "p"
toggle-view-mode = "t"
toggle-viewed = "v"

[keybindings.diff-view]
quit = "q"
comment = "c"
delete-comment = "d"
edit-comment = "e"
file-comment = "f"
toggle-view-mode = "t"
toggle-viewed = "v"
fold = "z"

[keybindings.comment-list]
quit = "q"
delete-comment = "d"
edit-comment = "e"

[keybindings.prompt-preview]
quit = "q"
copy-prompt = "y"
