hostname := `scutil --get LocalHostName`
username := `whoami`

default:
  @just -g -l

# ╔═══════════════════════════════╗
# ║            chezmoi            ║
# ╚═══════════════════════════════╝

# Show chezmoi diff
[group('chezmoi')]
diff:
  chezmoi diff

# Apply chezmoi changes
[group('chezmoi')]
apply:
  chezmoi apply

# ╔═══════════════════════════════╗
# ║              Nix              ║
# ╚═══════════════════════════════╝

# Apply nix-darwin configuration
[group('nix')]
darwin:
  sudo darwin-rebuild switch --flake ~/.config/nix#{{hostname}}

# Apply garbage collection to nix store
[group('nix')]
gc:
  nix store gc

# ╔═══════════════════════════════╗
# ║             utils             ║
# ╚═══════════════════════════════╝

# Update dotfiles and apply nix-darwin configuration
[group('utils')]
update:
  @just -g diff
  @just -g apply
  @just -g darwin
  @just -g gc
